---
# tasks file for win_service_manage
- name: Ensure "{{ service_name }}" is present
  win_service:
    name: "{{ service_name }}"
    state: "{{ service_state }}"
    start_mode: auto
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
  
